### ISSUE TITLE
a crash

### ISSUE THREAD

**Issue by amit1213** [jellysquid3/Phosphor#30] opened 2019-06-25 14:21 UTC
I got the following crash report and another one later

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/25/19 4:44 PM
Description: Updating screen events

java.lang.RuntimeException: error loading theme
	at drzhark.guiapi.GuiWidgetScreen.getInstance(GuiWidgetScreen.java:81)
	at drzhark.guiapi.GuiModScreen.setActive(GuiModScreen.java:155)
	at drzhark.guiapi.GuiModScreen.show(GuiModScreen.java:65)
	at drzhark.guiapi.GuiApiButton.func_146116_c(GuiApiButton.java:19)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:435)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
	at drzhark.guiapi.GuiWidgetScreen.getInstance(GuiWidgetScreen.java:70)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.xmlpull.v1.XmlPullParserException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at drzhark.guiapi.GuiWidgetScreen.getInstance(GuiWidgetScreen.java:81)
	at drzhark.guiapi.GuiModScreen.setActive(GuiModScreen.java:155)
	at drzhark.guiapi.GuiModScreen.show(GuiModScreen.java:65)
	at drzhark.guiapi.GuiApiButton.func_146116_c(GuiApiButton.java:19)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:435)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: drzhark.guiapi.GuiModSelect

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Gohamit'/298, l='MpServer', x=-735.13, y=95.31, z=931.51]]
	Chunk stats: MultiplayerChunkCache: 278, 278
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 19536 game time, 19536 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityMinecartChest['Minecart with Chest'/39296, l='MpServer', x=-659.50, y=29.06, z=920.50], EntityMinecartChest['Minecart with Chest'/39298, l='MpServer', x=-656.50, y=28.06, z=926.50], MoCEntityMole['Mole'/39683, l='MpServer', x=-666.50, y=65.00, z=990.50], EntityItem['item.tile.torch'/39433, l='MpServer', x=-720.57, y=43.00, z=944.08], EntityPlayerSP['Gohamit'/298, l='MpServer', x=-735.13, y=95.31, z=931.51], MoCEntityMole['Mole'/39441, l='MpServer', x=-755.50, y=70.00, z=931.50], EntitySheep['Sheep'/39203, l='MpServer', x=-665.50, y=63.00, z=887.50], EntitySheep['Sheep'/39204, l='MpServer', x=-665.50, y=65.00, z=886.50], EntitySheep['Sheep'/39205, l='MpServer', x=-667.49, y=71.28, z=882.51], EntitySheep['Sheep'/39206, l='MpServer', x=-668.50, y=72.00, z=879.50], MoCEntityScorpion['Scorpion'/40361, l='MpServer', x=-766.50, y=67.00, z=897.50], EntityItem['item.tile.torch'/39471, l='MpServer', x=-682.71, y=34.00, z=963.26], EntityItem['item.tile.torch'/39357, l='MpServer', x=-716.70, y=47.00, z=915.29], EntitySheep['Sheep'/39237, l='MpServer', x=-666.77, y=72.00, z=915.45], EntitySheep['Sheep'/39238, l='MpServer', x=-660.50, y=75.00, z=918.50], EntitySheep['Sheep'/39239, l='MpServer', x=-663.50, y=74.00, z=919.50], EntitySheep['Sheep'/39240, l='MpServer', x=-661.50, y=74.00, z=913.50], EntityItem['item.tile.doublePlant.syringa'/39881, l='MpServer', x=-677.97, y=64.00, z=942.59], EntityItem['item.tile.torch'/39376, l='MpServer', x=-728.71, y=37.00, z=905.69], MoCEntityBunny['Bunny'/39762, l='MpServer', x=-809.50, y=64.00, z=963.50], MoCEntityBunny['Bunny'/39763, l='MpServer', x=-810.50, y=64.00, z=962.50], EntityItem['item.tile.torch'/39389, l='MpServer', x=-720.50, y=47.00, z=926.13], MoCEntityEnt['Ent'/39390, l='MpServer', x=-714.50, y=63.00, z=935.50], MoCEntityBunny['Bunny'/39902, l='MpServer', x=-813.50, y=63.00, z=992.50], EntityPig['Pig'/39391, l='MpServer', x=-722.50, y=64.00, z=933.50], MoCEntityBunny['Bunny'/39903, l='MpServer', x=-810.50, y=63.00, z=989.50], EntityPig['Pig'/39392, l='MpServer', x=-720.50, y=64.00, z=935.50], MoCEntityFox['Fox'/39904, l='MpServer', x=-810.50, y=64.00, z=999.50], EntityPig['Pig'/39393, l='MpServer', x=-718.50, y=64.00, z=933.50], EntityPig['Pig'/39394, l='MpServer', x=-718.50, y=64.00, z=929.50], MoCEntityMole['Mole'/39522, l='MpServer', x=-778.00, y=68.85, z=917.23], MoCEntityMole['Mole'/39523, l='MpServer', x=-780.50, y=68.00, z=915.50], EntityItem['item.tile.torch'/39524, l='MpServer', x=-734.74, y=40.00, z=964.24], EntityItem['item.tile.torch'/39278, l='MpServer', x=-690.89, y=33.00, z=910.83], EntityItem['item.tile.torch'/39665, l='MpServer', x=-724.82, y=42.00, z=992.56], EntitySheep['Sheep'/39026, l='MpServer', x=-658.04, y=74.00, z=852.50], EntityItem['item.tile.torch'/39666, l='MpServer', x=-718.06, y=41.00, z=989.97], EntitySheep['Sheep'/39027, l='MpServer', x=-658.50, y=73.00, z=851.50], EntityItem['item.tile.torch'/39667, l='MpServer', x=-705.13, y=41.00, z=991.48], EntitySheep['Sheep'/39028, l='MpServer', x=-661.44, y=73.92, z=852.50], EntitySheep['Sheep'/39029, l='MpServer', x=-658.50, y=73.00, z=850.50], MoCEntityMole['Mole'/39414, l='MpServer', x=-750.50, y=68.00, z=918.50], MoCEntityMole['Mole'/39415, l='MpServer', x=-751.50, y=68.00, z=918.50], EntityCow['Cow'/39416, l='MpServer', x=-754.50, y=69.00, z=918.50], EntityCow['Cow'/39417, l='MpServer', x=-754.50, y=69.00, z=917.50], EntityCow['Cow'/39418, l='MpServer', x=-753.50, y=68.00, z=915.50], EntityCow['Cow'/39419, l='MpServer', x=-751.50, y=68.00, z=915.50], EntityItem['item.tile.torch'/39548, l='MpServer', x=-697.13, y=40.00, z=979.26], MoCEntityMole['Mole'/39805, l='MpServer', x=-771.50, y=67.00, z=1004.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 800455432 bytes (763 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | orbis-lib           | 0.2.0        | orbis-lib-1.12.2-0.2.0+build74.jar            | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJA | aether              | 0.2.1        | Aether-2-Mod-1.12.2.jar                       | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJA | architecturecraft   | @VERSION@    | ArchitectureCraft-Mod-1.12.2.jar              | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2427   | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar | None                                     |
	| UCHIJA | cfm                 | 6.2.1        | cfm-6.2.1-mc1.12.2.jar                        | None                                     |
	| UCHIJA | customnpcs          | 1.12         | CustomNPCs_1.12.2(30Jan19).jar                | None                                     |
	| UCHIJA | journeymap          | 1.12.2-5.5.4 | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| UCHIJA | radixcore           | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UCHIJA | mca                 | 1.12.2-5.3.1 | Minecraft-Comes-Alive-Mod-1.12.2.jar          | None                                     |
	| UCHIJA | mocreatures         | 12.0.5       | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHIJA | roguelike           | 1.8.0        | Roguelike-Dungeons-Mod-1.12.2.jar             | None                                     |
	| UCHIJA | treechopper         | 1.2.4        | Tree-Chopper-Mod-1.12.2.jar                   | None                                     |
	| UCHIJA | twilightforest      | 3.9.888      | Twilight-Forest-Mod-1.12.2.jar                | None                                     |
	| UCHIJA | veinminer           | 0.38.1       | Vein-Miner-Mod-1.12 (1).jar                   | None                                     |
	| UCHIJA | veinminermodsupport | 0.38.1       | Vein-Miner-Mod-1.12 (1).jar                   | None                                     |
	| UCHIJA | phosphor-lighting   | 1.12.2-0.2.4 | phosphor-1.12.2-0.2.4+build46.jar             | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.57' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.57, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 6/25/19 4:52 PM
Description: Ticking entity

java.lang.ClassCastException: com.google.common.base.Present cannot be cast to java.lang.Boolean
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: mca:villagermca (mca.entity.EntityVillagerMCA)
	Entity ID: 22051
	Entity Name: Steve
	Entity's Exact location: -789.50, 65.00, 1226.50
	Entity's Block location: World: (-790,65,1226), Chunk: (at 10,4,10 in -50,76; contains blocks -800,0,1216 to -785,255,1231), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Gohamit'/285, l='MpServer', x=-786.52, y=73.58, z=1177.75]]
	Chunk stats: MultiplayerChunkCache: 337, 337
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25565 game time, 25565 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityHorse['Horse'/17160, l='MpServer', x=-846.50, y=65.00, z=1212.50], EntityHorse['Horse'/17161, l='MpServer', x=-846.50, y=65.00, z=1212.50], EntityHorse['Horse'/17162, l='MpServer', x=-843.50, y=65.00, z=1213.50], EntityPlayerSP['Gohamit'/285, l='MpServer', x=-786.52, y=73.58, z=1177.75], EntitySquid['Squid'/18320, l='MpServer', x=-724.22, y=62.60, z=1182.99], EntitySquid['Squid'/18321, l='MpServer', x=-720.23, y=62.25, z=1179.42], EntitySquid['Squid'/18323, l='MpServer', x=-721.97, y=61.72, z=1188.60], EntityItem['item.item.seeds'/25237, l='MpServer', x=-759.65, y=61.00, z=1160.88], EntityVillagerMCA['Steve'/22051, l='MpServer', x=-789.50, y=65.00, z=1226.50], MoCEntityMole['Mole'/11189, l='MpServer', x=-744.46, y=64.00, z=1091.90], EntityHorse['Horse'/11961, l='MpServer', x=-790.28, y=63.00, z=1178.51], EntityHorse['Horse'/11962, l='MpServer', x=-787.99, y=63.00, z=1181.01], EntityHorse['Horse'/11963, l='MpServer', x=-790.29, y=63.00, z=1179.61], MoCEntityMole['Mole'/11584, l='MpServer', x=-767.50, y=64.00, z=1117.50], EntityItem['item.item.seeds'/25925, l='MpServer', x=-750.26, y=63.00, z=1211.11], EntityItem['item.item.seeds'/25926, l='MpServer', x=-747.78, y=63.00, z=1211.03], EntityHorse['Horse'/11610, l='MpServer', x=-762.29, y=65.00, z=1157.78], EntityHorse['Horse'/11868, l='MpServer', x=-785.44, y=64.00, z=1152.80], MoCEntityBunny['Bunny'/16476, l='MpServer', x=-814.50, y=64.00, z=1087.50], EntityHorse['Horse'/11869, l='MpServer', x=-786.03, y=64.00, z=1153.83], EntityHorse['Horse'/11870, l='MpServer', x=-791.50, y=64.00, z=1156.50], EntityHorse['Horse'/11871, l='MpServer', x=-791.50, y=64.00, z=1158.50], MoCEntityMole['Mole'/11241, l='MpServer', x=-727.50, y=74.00, z=1108.50], MoCEntityMole['Mole'/17138, l='MpServer', x=-846.88, y=63.00, z=1115.95], EntityCow['Cow'/11132, l='MpServer', x=-717.81, y=64.00, z=1088.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 817129704 bytes (779 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | orbis-lib           | 0.2.0        | orbis-lib-1.12.2-0.2.0+build74.jar            | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJA | aether              | 0.2.1        | Aether-2-Mod-1.12.2.jar                       | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJA | architecturecraft   | @VERSION@    | ArchitectureCraft-Mod-1.12.2.jar              | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2427   | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar | None                                     |
	| UCHIJA | cfm                 | 6.2.1        | cfm-6.2.1-mc1.12.2.jar                        | None                                     |
	| UCHIJA | customnpcs          | 1.12         | CustomNPCs_1.12.2(30Jan19).jar                | None                                     |
	| UCHIJA | journeymap          | 1.12.2-5.5.4 | journeymap-1.12.2-5.5.4.jar                   | None                                     |
	| UCHIJA | radixcore           | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UCHIJA | mca                 | 1.12.2-5.3.1 | Minecraft-Comes-Alive-Mod-1.12.2.jar          | None                                     |
	| UCHIJA | mocreatures         | 12.0.5       | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHIJA | roguelike           | 1.8.0        | Roguelike-Dungeons-Mod-1.12.2.jar             | None                                     |
	| UCHIJA | treechopper         | 1.2.4        | Tree-Chopper-Mod-1.12.2.jar                   | None                                     |
	| UCHIJA | twilightforest      | 3.9.888      | Twilight-Forest-Mod-1.12.2.jar                | None                                     |
	| UCHIJA | veinminer           | 0.38.1       | Vein-Miner-Mod-1.12 (1).jar                   | None                                     |
	| UCHIJA | veinminermodsupport | 0.38.1       | Vein-Miner-Mod-1.12 (1).jar                   | None                                     |
	| UCHIJA | phosphor-lighting   | 1.12.2-0.2.4 | phosphor-1.12.2-0.2.4+build46.jar             | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.57' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.57, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by jellysquid3** [comment] 2019-06-25 17:22
Why do you think this is related to Phosphor? Can you reproduce this crash without Phosphor installed?

**Comment by jellysquid3** [comment] 2019-06-25 17:40
I've also noticed that many of your installed mods come from sources other than official Curseforge page. The issue with MCA seems to be due to not using the latest version, which often happens when you use unofficial mirrors. Please download your mods from Curseforge and update all your mods to the latest version.

**Comment by jellysquid3** [comment] 2019-07-01 04:17
Due to this issue appearing to be a result of an issue outside of our control-- being possibly a missing dependency of another mod-- and the lack of a followup, I will close this issue as not our problem.

**Closed by jellysquid3** 2019-07-01 04:17 UTC
