### ISSUE TITLE
Crash (ticking memory connection)

### ISSUE THREAD

**Issue by jayhilaly** [jellysquid3/Phosphor#23] opened 2019-06-09 20:31 UTC
Unfortunately, I am not able to play on any world. I have removed forge and reinstalled it but to no avail. Tried checking many threads on this issue but haven't helped. 

Before the world loads the terrain, it crashes and mentions the below report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.1.6+build31.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/9/19 11:17 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at A.v.a(SourceFile:117)
	at D.c.a(SourceFile:44)
	at D.c.a(SourceFile:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_c_a_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at A.v.a(SourceFile:117)
	at D.c.a(SourceFile:44)
	at D.c.a(SourceFile:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_c_a_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@7d408d42
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1551316680 bytes (1479 MB) / 4865392640 bytes (4640 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version         | Source                                       | Signature                                |
	|:------ |:----------------- |:--------------- |:-------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2          | minecraft.jar                                | None                                     |
	| LCHIJA | mcp               | 9.42            | minecraft.jar                                | None                                     |
	| LCHIJA | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2838.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2838    | forge-1.12.2-14.23.5.2838.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | orbis-lib         | 0.2.0           | orbis-lib-1.12.2-0.2.0+build42.jar           | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | aether            | 0.2.0           | aether_ii-1.12.2-0.2.0+build42-universal.jar | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | ism               | 2.6.1 MC-1.12.2 | ism-2.6.1 MC-1.12.2 (2).jar                  | None                                     |
	| LCHIJA | twilightforest    | 3.8.689         | twilightforest-1.12.2-3.8.689-universal.jar  | None                                     |
	| LCHIJA | phosphor-lighting | 1.12.2-0.1.6    | phosphor-1.12.2-0.1.6+build31.jar            | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.1.6+build31.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['7JahRed7'/4360, l='Copy of My World', x=166.50, y=73.00, z=192.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jellysquid3** [comment] 2019-06-09 20:38
You are using an old version of Phosphor and the Aether II. Please upgrade to the latest of both. If you are still able to reproduce it, please remove all other mods and install Phosphor manually (by grabbing it from CurseForge and dropping it into your `mods` directory), then upload the new crash log.

**Comment by jayhilaly** [comment] 2019-06-10 15:33
I did as you have mentioned for Aether II mod and phosphor is now to the most updated version; however, I seem to still get a crash report as per the below: 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 6/10/19 6:31 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at A.v.a(SourceFile:117)
	at D.c.a(SourceFile:44)
	at D.c.a(SourceFile:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_164_c_a_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at A.v.a(SourceFile:117)
	at D.c.a(SourceFile:44)
	at D.c.a(SourceFile:92)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_164_c_a_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@a41f3dc
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1405155552 bytes (1340 MB) / 4798283776 bytes (4576 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version         | Source                                          | Signature                                |
	|:------ |:----------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2          | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp               | 9.42            | minecraft.jar                                   | None                                     |
	| LCHIJA | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2838    | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | orbis-lib         | 0.2.0           | orbis-lib-1.12.2-0.2.0+build74.jar              | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | aether            | 0.2.1           | aether_ii-1.12.2-0.2.1+build74-universal.jar    | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | ism               | 2.6.1 MC-1.12.2 | ism-2.6.1 MC-1.12.2 (2).jar                     | None                                     |
	| LCHIJA | journeymap        | 1.12.2-5.5.4    | journeymap-1.12.2-5.5.4.jar                     | None                                     |
	| LCHIJA | twilightforest    | 3.8.689         | twilightforest-1.12.2-3.8.689-universal (1).jar | None                                     |
	| LCHIJA | phosphor-lighting | 1.12.2-0.2.4    | phosphor-1.12.2-0.2.4+build46.jar               | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['7JahRed7'/2107, l='New World', x=-12.50, y=66.00, z=99.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jellysquid3** [comment] 2019-06-10 17:23
This appears to be a problem with the Instant Structures Mod you have installed and is reproducible with or without the Aether II or Phosphor installed. You will have to remove that mod for the time being until the issue is fixed on their side.

**Closed by jellysquid3** 2019-06-10 17:23 UTC
Labels: awaiting feedback
